spring:
  application:
    name: task-tracker-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic: ${KAFKA_TOPIC}

task-tracker-backend:
  jwt:
    secret_key: ${JWT_SECRET}
    access_token_expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}

logging:
  level:
    root: info
