spring:
  application:
    name: task-tracker-scheduler

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic: ${KAFKA_TOPIC}

scheduler:
  cron: ${SCHEDULER_CRON}
  cron-new: ${SCHEDULER_CRON_NEW}
  tasks-count-limit: ${SCHEDULER_TASKS_COUNT_LIMIT}
  message-title: ${SCHEDULER_MESSAGE_TITLE}
